on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Add Umbraco Pre-release NuGet
      run: dotnet nuget add source https://www.myget.org/F/umbracoprereleases/api/v3/index.json -n UmbracoPrereleases
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
